#!/bin/sh
docker run -it --rm -p 8888:8888 \
    -e GRANT_SUDO=yes \
    --user root \
    -v /Users/asm/Documents/JupyterData/:/home/jovyan/work \
    --name jupyter-analysis \
    morria/jupyter:latest

