#!/bin/sh
sudo docker run -it --rm -p 8888:8888 \
    -e GRANT_SUDO=yes \
    --user root \
    --user 1000 --group-add users \
    -v /home/asm/Documents/JupyterData/:/home/jovyan/work \
    --name jupyter-analysis \
    morria/jupyter:latest
